# Generated by Django 3.2 on 2022-02-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
