# Generated by Django 3.2 on 2022-02-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_inventory', '0002_userinventory_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
