# Generated by Django 3.2 on 2022-02-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20220206_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunityMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('message_content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('like', models.BooleanField(blank=True, default=False)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='profiles.userprofile')),
            ],
        ),
    ]
