# Generated by Django 3.2 on 2022-02-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderunique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUnique',
        ),
    ]
