# Generated by Django 3.2 on 2022-02-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='subscription',
            new_name='unique',
        ),
    ]
