# Generated by Django 3.2 on 2022-02-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_subscription_plan_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='unique',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
