# Generated by Django 3.2 on 2022-02-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_inventory', '0001_initial'),
        ('checkout_unique_5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderunique',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='orderunique',
            name='user_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_unique', to='user_inventory.userinventory'),
        ),
    ]
