# Generated by Django 3.2 on 2022-02-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_unique_5', '0002_auto_20220221_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitemunique',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems_unique', to='checkout_unique_5.orderunique'),
        ),
    ]
