# Generated by Django 3.2 on 2022-02-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
