# Generated by Django 3.2 on 2022-02-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
